### ISSUE TITLE
Help request: Successful k8 deployment as sidecar

### ISSUE THREAD

**Issue by terrypireaux** [gubernator-io/gubernator#51]
Looking for some example side car configs in k8s for running Gubernator. Currently having issues with peer discovery. 

# Error on health check 

```
{"status":"unhealthy","message":"this instance is not found in the peer list","peer_count":3,"advertise_address":""}
```

# Current ENV

```
  env:
    - name: GUBER_GRPC_ADDRESS
      value: "0.0.0.0:9990"
    - name: GUBER_HTTP_ADDRESS
      value: "0.0.0.0:9980"
    - name: GUBER_INSTANCE_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: GUBER_PEER_DISCOVERY_TYPE
      value: "k8s"
    - name: GUBER_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: GUBER_K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: GUBER_K8S_POD_PORT
      value: "9990"
    - name: GUBER_K8S_WATCH_MECHANISM
      value: "pods" # also tried "endpoints" to same result
    - name: GUBER_K8S_ENDPOINTS_SELECTOR
      value: "app.kubernetes.io/instance={someservicename},app.kubernetes.io/name={someservicename}"
```
